server:
  port: 8083
  error:
    include-stacktrace: never
  servlet:
    context-path: /products
spring:
  datasource:
    url: ${ECRITIC_DB_URL:jdbc:postgresql://localhost:5433/ecritic}
    username: ${ECRITIC_DB_USERNAME:root}
    password: ${ECRITIC_DB_PASSWORD:root}
  jpa:
    database: POSTGRESQL
  error:
    include-stacktrace: never
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:af1ce60c0f7}

application:
  properties:
    redis:
      brand-expiration-time: 1440
      brands-expiration-time: 60
      brands-count-expiration-time: 60